#!/bin/bash
#
# Wrapper script which simply runs the following:
#  java edu.jhu.nlp.eval.SignificanceTests
#
# The script requires maven in order to grab the dependencies and add
# them to the classpath. Classpath resolution was adapted from the
# mvnrun script: https://github.com/nqzero/mvnrun.
#

command -v mvn >/dev/null 2>&1 || { echo >&2 "The 'mvn' command (i.e Maven) is required, but not installed.  Aborting."; exit 1; }

: ${output:="/dev/null"}

pomxml="
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>sigtest</groupId>
  <artifactId>sigtest</artifactId>
  <version>1.0</version>
  <dependencies>
    <dependency>
      <groupId>edu.jhu.pacaya-nlp</groupId>
      <artifactId>pacaya-nlp</artifactId>
      <version>3.1.5</version>
    </dependency>
  </dependencies>
</project>
"


cp=-
read cp < <(
    mvn dependency:resolve dependency:build-classpath -f <(echo "${pomxml}") -Dmdep.outputFile=/dev/fd/3 3>&1 > ${output}
)

if [ "$cp" == - ]; then
   echo "mvn failed to resolve ... exiting"
   exit 1;
fi

java -cp "${cp}" edu.jhu.nlp.eval.SignificanceTests ${@}
